"use client";

import type { ComponentType } from "react";
import { Sparkles } from "lucide-react";

import { useAuth } from "@/hooks/use-auth";
import { useInsightsLayoutPrefs } from "@/hooks/use-insights-layout-prefs";
import { useChartDomainStats } from "@/hooks/use-chart-domain-stats";
import type { ChartOverlayKey } from "@/lib/dashboard-layout";
import type { MetricStatusMetricId } from "@/lib/insights/metric-status-registry";
import type { DataSummary } from "@/lib/analytics/trends";
import { HealthChartDynamic } from "@/components/charts/health-chart-dynamic";
import { MetricStatStrip } from "@/components/insights/metric-stat-strip";
import { MetricStatusCard } from "@/components/insights/metric-status-card";

/**
 * v1.18.1 (B1 / B2) — one canonical chart block on `/insights/recovery`.
 *
 * The rebuilt recovery page reads exactly like every other metric page
 * (blood pressure, pulse, the HealthKit scaffold): each present device
 * signal renders its own block carrying the four building blocks the
 * canonical structure demands — a short explanatory line, the max /
 * median / mean stat strip, the same `<HealthChartDynamic>` chart with the
 * identical 7 / 30 / 90 / All toggle, and a per-chart `<MetricStatusCard>`
 * assessment (B2: multiple charts → multiple matching texts, generated by
 * the generic metric-status path rather than hard-coded).
 *
 * Device-native scores carry no fixed target band, so no `MetricTargetSummary`
 * is mounted here; the assessment + the user's own baseline carry the read.
 * Each block owns its own `useChartDomainStats` so brushing one chart's range
 * never bleeds into a sibling's stat strip.
 */
export interface RecoveryMetricBlockProps {
  /** The DB `MeasurementType` the chart + strip read. */
  type: string;
  /** Per-block chart-overlay slot so the chart-cog popover persists. */
  chartKey: ChartOverlayKey;
  /** The registry metric id the per-chart assessment keys on. */
  statusMetric: MetricStatusMetricId;
  /** Localised block title (chart title + stat-strip header). */
  title: string;
  /** Short explanatory line beneath the title — what the metric refers to. */
  explainer: string;
  /** Leading glyph, shared across title / strip / chart. */
  icon: ComponentType<{ className?: string }>;
  /** Single canonical chart line colour. */
  color: string;
  /** Unit suffix (e.g. `bpm`, `kJ`, `score`). */
  unit: string;
  /** Analytics summary for `type`; null until the read lands. */
  summary: DataSummary | null;
  /** Decimal precision for the stat-strip values. Defaults to 1. */
  fractionDigits?: number;
}

export function RecoveryMetricBlock({
  type,
  chartKey,
  statusMetric,
  title,
  explainer,
  icon: Icon,
  color,
  unit,
  summary,
  fractionDigits,
}: RecoveryMetricBlockProps) {
  const { user, isAuthenticated } = useAuth();
  const { compareBaseline } = useInsightsLayoutPrefs(isAuthenticated);
  const { statsByType, onVisibleStats } = useChartDomainStats();

  return (
    <section data-slot={`recovery-block-${type}`} className="space-y-3">
      <div className="space-y-1">
        <div className="flex items-center gap-2">
          <Icon
            className="text-muted-foreground size-4 shrink-0"
            aria-hidden="true"
          />
          {/* v1.18.6 — block title is an `<h2>` (at `text-base`): the per-group
              sub-headings were removed, so each block now sits directly under
              the page `<h1>` from `SubPageShell`. Promoting it from `<h3>` keeps
              the recovery page's heading outline strictly nested (h1 → h2)
              with no skipped level. */}
          <h2 className="text-base font-semibold">{title}</h2>
        </div>
        <p className="text-foreground text-sm leading-relaxed">{explainer}</p>
      </div>

      <MetricStatStrip
        summary={summary}
        unit={unit}
        fractionDigits={fractionDigits}
        seriesLabel={title}
        icon={Icon}
        windowStats={statsByType?.[type] ?? null}
      />

      <HealthChartDynamic
        chartKey={chartKey}
        types={[type]}
        title={title}
        titleIcon={Icon}
        colors={[color]}
        unit={unit}
        yAxisUnit={unit}
        compareBaseline={compareBaseline}
        userTimezone={user?.timezone}
        onVisibleStats={onVisibleStats}
      />

      <MetricStatusCard
        metric={statusMetric}
        icon={<Sparkles className="h-5 w-5" />}
        enabled
      />
    </section>
  );
}
